#name: Publish to PyPI
#
#on:
#  push:
#    branches:
#      - "github_actions_publish"
#  release:
#    types: [published]
#
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: "3.10"
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - name: Run tests
#      run: pytest -v --tb=native -p no:warnings --cov-fail-under 99 --cov
#
#    - name: Package project
#      run: python setup.py sdist bdist_wheel
#
#    - name: Show package
#      run: ls -lh dist/
#
##    - name: Upload distributions
##      env:
##        TWINE_USERNAME: __token__
##        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
##      run: twine upload dist/*
