language: python
sudo: false
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - pip install -U pip
  - pip install python-coveralls
  - pip install -U -r requirements.txt
script:
  - pytest -v --tb=native -p no:warnings --cov-fail-under 90 --cov
after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    python: '3.8'
    repo: thesimj/envyaml
