name: CI/CD Pipeline

on: [ push,  pull_request, release ]

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '2.7', '3.6','3.7', '3.8', '3.9', '3.10', 'pypy-2.7', 'pypy-3.8' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python ${{ matrix.os }} - ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v --tb=native -p no:warnings --cov-fail-under 90 --cov

  pip-publish:
    needs: build-and-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v --tb=native -p no:warnings --cov-fail-under 99 --cov

      - name: Package project
        run: python setup.py sdist bdist_wheel

      - name: Show package
        run: ls -lh dist/

      - name: Show Github Ref
        run: echo ${{ github.ref }}
