name: EnvYaml CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]

  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

  release:
    types: [ published ]

# specify jobs to done
jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '2.7', '3.6','3.7', '3.8', '3.9', '3.10', 'pypy-2.7', 'pypy-3.8' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python ${{ matrix.os }} - ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v --tb=native -p no:warnings --cov-fail-under 90 --cov

  pip-publish:
    needs: build-and-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Show Github Ref
        run: echo ${{ github.ref }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v --tb=native -p no:warnings --cov-fail-under 90 --cov

      - name: Package project
        run: python setup.py sdist bdist_wheel

      - name: Show package
        run: ls -lh dist/

      - name: Publish package to PyPi
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*

